AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge Rule creation

Resources:
  TintMasterBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: GTech-AD-Posting-tint-master
      Description: AWS EventBridge rule for Tint Master
      ScheduleExpression: "cron(0 12 ? * 2,5 *)"
      State: ENABLED
      Targets:
        - Arn: !ImportValue gtech-ad-posting-app-lambda-func-ARN
          Id: GTech-AD-Posting-Schedule
          Input: '{"company_name": "tint_master"}'
