AWSTemplateFormatVersion: '2010-09-09'
Description: Sets up IAM Role for dmp-ping-process Lambda.

Parameters:
  Name:
    Type: String
    Default: lambda
    Description: Project name

Resources:
  GTechSecretManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'Store the GTech App related secrets in SecretManager'
      Name: gtechadapp/credentials
      SecretString: "{\"gtech_login_url\": \"\", \"gtech_ad_url\": \"\", \"tint_master_id\": \"\", \"tint_master_pw\": \"\"}"
  GTechAutoPostingLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy for GTECH Posting Lambda
      ManagedPolicyName: !Sub "gtech-ad-posting-app-lambda-policy-${AWS::Region}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: "AllowS3GetObject"
            Action:
              - s3:*
              - s3-object-lambda:*
            Resource:
              - arn:aws:s3:::gtech-posting-app
              - arn:aws:s3:::gtech-posting-app/*
          - Effect: Allow
            Sid: "Allow SecretManager"
            Action:
              - secretsmanager:ListSecrets
              - secretsmanager:ListSecretVersionIds
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - !Ref GTechSecretManager
  GTechAutoPostingLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub "gtech-ad-posting-app-lambda-role-${AWS::Region}"
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - !Ref GTechAutoPostingLambdaPolicy

Outputs:
  GTechAutoPostingLambdaRoleARN:
    Value: !GetAtt GTechAutoPostingLambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ARN"