AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Name:
    Type: String
    Default: lambda
    Description: Project name

Mappings:
  Constant:
    Value:
      FuncName: gtech-auto-posting-app-lambda-SAM
      LambdaMemorySize: 1024

Globals:
  Function:
    Runtime: python3.9
    Architectures:
      - x86_64
    Timeout: 300
    CodeUri: .

Resources:
  GTechAutoPostingLambda:
    Type: AWS::Serverless::Function
#    Properties:
#      Description: Setting up gtech-auto-posting-app Lambda
#      FunctionName: !FindInMap [ Constant, Value, FuncName ]
#      Handler: !Join [ '.', [ !FindInMap [ Constant, Value, FuncName ], 'lambda_handler' ] ]
#      Role: !ImportValue gtech-auto-posting-app-lambda-iam-role-ARN
#      MemorySize: !FindInMap [ Constant, Value, LambdaMemorySize ]

    Properties:
      Description: Setting up gtech-auto-posting-app Lambda
      FunctionName: !FindInMap [ Constant, Value, FuncName ]
      PackageType: Image
      Role: !ImportValue gtech-auto-posting-app-lambda-iam-role-ARN
      MemorySize: !FindInMap [ Constant, Value, LambdaMemorySize ]
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda_code
      DockerTag: GTlambda:latest

Outputs:
  GTechAutoPostingLambdaARN:
    Description: gtech-auto-posting-app Lambda ARN
    Value: !GetAtt  GTechAutoPostingLambda.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SAM-ARN"
  GTechAutoPostingLambdaName:
    Description: gtech-auto-posting-app Lambda Name
    Value: !Ref GTechAutoPostingLambda
    Export:
      Name: !Sub "${AWS::StackName}-SAM-Name"